repadmin /replicate ares fwdc01 dc=manchester,dc=edu
repadmin /replicate ares fwdc02 dc=manchester,dc=edu
repadmin /replicate ares kronos dc=manchester,dc=edu
repadmin /replicate ares momus dc=manchester,dc=edu
repadmin /replicate ares zeus dc=manchester,dc=edu
repadmin /replicate fwdc01 ares dc=manchester,dc=edu
repadmin /replicate fwdc01 fwdc02 dc=manchester,dc=edu
repadmin /replicate fwdc01 kronos dc=manchester,dc=edu
repadmin /replicate fwdc01 momus dc=manchester,dc=edu
repadmin /replicate fwdc01 zeus dc=manchester,dc=edu
repadmin /replicate fwdc02 ares dc=manchester,dc=edu
repadmin /replicate fwdc02 fwdc01 dc=manchester,dc=edu
repadmin /replicate fwdc02 kronos dc=manchester,dc=edu
repadmin /replicate fwdc02 momus dc=manchester,dc=edu
repadmin /replicate fwdc02 zeus dc=manchester,dc=edu
repadmin /replicate kronos ares dc=manchester,dc=edu
repadmin /replicate kronos fwdc01 dc=manchester,dc=edu
repadmin /replicate kronos fwdc02 dc=manchester,dc=edu
repadmin /replicate kronos momus dc=manchester,dc=edu
repadmin /replicate kronos zeus dc=manchester,dc=edu
repadmin /replicate momus ares dc=manchester,dc=edu
repadmin /replicate momus fwdc01 dc=manchester,dc=edu
repadmin /replicate momus fwdc02 dc=manchester,dc=edu
repadmin /replicate momus kronos dc=manchester,dc=edu
repadmin /replicate momus zeus dc=manchester,dc=edu
repadmin /replicate zeus ares dc=manchester,dc=edu
repadmin /replicate zeus fwdc01 dc=manchester,dc=edu
repadmin /replicate zeus fwdc02 dc=manchester,dc=edu
repadmin /replicate zeus kronos dc=manchester,dc=edu
repadmin /replicate zeus momus dc=manchester,dc=edu
repadmin /replicate pontus ares dc=manchester,dc=edu
repadmin /replicate pontus fwdc01 dc=manchester,dc=edu
repadmin /replicate pontus fwdc02 dc=manchester,dc=edu
repadmin /replicate pontus kronos dc=manchester,dc=edu
repadmin /replicate pontus momus dc=manchester,dc=edu
repadmin /replicate pontus zeus dc=manchester,dc=edu
pause